# Generated by Django 6.0.1 on 2026-01-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
