# Generated by Django 6.0.1 on 2026-01-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0003_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Chưa phân loại', max_length=100),
        ),
    ]
