# Generated by Django 6.0.1 on 2026-01-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0004_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Hành động', 'Hành động'), ('Kinh dị', 'Kinh dị'), ('Tình cảm', 'Tình cảm'), ('Hoạt hình', 'Hoạt hình'), ('Viễn tưởng', 'Viễn tưởng')], default='Hành động', max_length=100),
        ),
    ]
