# Generated by Django 6.0.1 on 2026-02-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('movie', 'Phim Lẻ'), ('series', 'Phim Bộ')], default='movie', max_length=10),
        ),
    ]
