# Generated by Django 6.0.1 on 2026-02-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0010_seat_held_by_seat_held_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='held_by',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='held_until',
        ),
    ]
